services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    tty: true
    user: "995:994"
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - /etc/mysql/conf.d/:/etc/mysql/conf.d
    env_file:
      - .env

  mpcc:
    image: ghcr.io/mprov-ng/mprov-control-center:dev
    #image: localhost/mprov-control-center:dev
    restart: unless-stopped
    pull_policy: always
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 10s
      retries: 8
    depends_on:
      db:
        condition: service_started
    volumes: 
      # for dev only, Documentation Pending.
      #  General steps:
      #    - start the stack with this commented out.
      #    - run `docker cp mprov-compose-mpcc-1:/var/www/mprov_control_center /root/mprov_control_cetner`
      #    - once all the jobserver jobs complete, down the stack
      #    - uncomment this line.
      #    - PROFIT!
      - /root/mprov_control_center:/var/www/mprov_control_center
      #- mpcc-media:/var/www/mprov_control_center/media
      - mprov-conf:/etc/mprov/
    env_file:
     - .env
    ports:
     - 8000:80
     - 4343:443
    hostname: ${MPROV_MPCC_HOSTNAME}
    command: sh -c '/wait-for-it.sh -t 0 db:3306 -- /var/www/mprov_control_center/install_scripts/init_mpcc.sh -d'
    
  jobserver:
    image: ghcr.io/mprov-ng/mprov-jobserver:latest
    # image: localhost/mprov-jobserver:dev
    cgroup: host
    restart: unless-stopped
    pull_policy: always
    depends_on:
      mpcc:
        condition: service_healthy
        #systemd: true
    network_mode: host
    tty: true
    volumes:
      - mprov-conf:/etc/mprov/
      - /export:/export
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /etc/genders:/etc/genders
      - /var/lib/mprov:/var/lib/mprov
    env_file:
      - .env
    user: ${UID:-0}:${GID:-0}
    privileged: true
    hostname: ${MPROV_JOBSERVER_HOSTNAME}
    # we wait for localhost here because we are host networking and all services are running from the same .
    command: sh -c '/wait-for-it.sh -t 0 localhost:80 -- /sbin/init'


volumes:
  mprov-conf:
  # db:
  # mpcc-media:

