services:
  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    env_file:
      - stack.env

  mpcc:
    image: ghcr.io/mprov-ng/mprov-control-center:dev
    restart: unless-stopped
    depends_on:
      db:
    volumes: 
      - mpcc-media:/var/www/mprov_control_center/media
    env_file:
     - stack.env
    ports:
     - 80:80
     - 443:443
    command: sh -c '/wait-for-it.sh -t 0 db:3306 -- /var/www/mprov_control_center/install_scripts/init_mpcc.sh -d'

  jobserver:
    image: ghcr.io/mprov-ng/mprov-jobserver:dev
    restart: unless-stopped
    volumes:
      - /home/export:/export
    env_file:
      - stack.env
    ports:
      - 8080:8080
    user: ${UID:-0}:${GID:-0}
    privileged: true
    hostname: mprov-jobserver01


volumes:
  db:
  mpcc-media:

