services:
  db:
    image: mariadb:10.4
    restart: unless-stopped
    tty: true
    volumes:
      - db:/var/lib/mysql
    env_file:
      - stack.env

  mpcc:
    image: ghcr.io/mprov-ng/mprov-control-center:dev
    #image: localhost/mprov-control-center:dev
    restart: unless-stopped
    tty: true
    depends_on:
      db:
        condition: service_started
    volumes: 
    # for dev only.
    #- /root/mprov_control_center:/var/www/mprov_control_center
      - mpcc-media:/var/www/mprov_control_center/media
      - mprov-conf:/etc/mprov/
    env_file:
     - stack.env
    ports:
     - 80:80
     - 443:443
    hostname: ${MPROV_MPCC_HOSTNAME}
    command: sh -c '/wait-for-it.sh -t 0 db:3306 -- /var/www/mprov_control_center/install_scripts/init_mpcc.sh -d'
    
  jobserver:
    image: ghcr.io/mprov-ng/mprov-jobserver:dev
    # image: localhost/mprov-jobserver:dev
    cgroup: host
    restart: unless-stopped
    depends_on:
      mpcc:
        condition: service_started
        #systemd: true
    network_mode: host
    tty: true
    volumes:
      - mprov-conf:/etc/mprov/
      - /home/export:/export
      - /sys/fs/cgroup:/sys/fs/cgroup
    env_file:
      - stack.env
    user: ${UID:-0}:${GID:-0}
    privileged: true
    hostname: ${MPROV_JOBSERVER_HOSTNAME}
    # we wait for localhost here because we are host networking and all services are running from the same stack.
    command: sh -c '/wait-for-it.sh -t 0 localhost:80 -- /sbin/init'


volumes:
  mprov-conf:
  db:
  mpcc-media:

